version: '3.8'
services:
  nest:
    build: .
    depends_on:
      db:
        condition: service_healthy
        required: true
    networks:
      - nestjs
    env_file:
      - .env
    restart: on-failure
    ports:
      - 3000:3000
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
    volumes:
      - psql_data:/var/lib/postgresql/data
    networks:
      - nestjs
    ports:
      - 5432:5432
volumes:
  psql_data:
    driver: local
networks:
  nestjs:
